[DEFAULT]
bantime = 1h
findtime = 10m
maxretry = 5
ignoreip = 127.0.0.1/8 ::1 86.104.249.235

[sshd]
enabled = true
port = ssh
logpath = %(sshd_log)s
backend = systemd
maxretry = 5

[rehab-nginx-probes]
enabled = true
port = http,https
filter = rehab-nginx-probes
logpath = /var/log/nginx/access.log
backend = auto
maxretry = 5
findtime = 10m
bantime = 1h
